reddit:
  enabled: True
  info: False
  image: True
  video: True
instagram:
  enabled: True
  info: True
  image: True
  thumbnail: False
  video: True
youtube:
  enabled: True
  info: True
  thumbnail: True
msgtypes:
  text: True
  notice: False
